#!/bin/bash

action=$(echo -e "Install\nRemove\nList\nSearch" | fzf --prompt="Flatpak Action> ")
case "$action" in
    Install)
        app=$(flatpak remote-ls --app | awk '{print $1}' | fzf --prompt="Select App to Install> ")
        [[ -n "$app" ]] && flatpak install -y "$app"
        ;;
    Remove)
        app=$(flatpak list | awk '{print $1}' | fzf --prompt="Select App to Remove> ")
        [[ -n "$app" ]] && flatpak uninstall -y "$app"
        ;;
    List)
        flatpak list | less
        ;;
    Search)
        term=$(fzf --prompt="Search Term> ")
        flatpak search "$term" | less
        ;;
    *)
        echo "No action selected."
        ;;
esac
