#!/bin/bash

action=$(echo -e "Install\nRemove\nPurge\nClean" | fzf --prompt="pmm>apt> ")
case "$action" in
    Install)
        app=$(apt list | awk -F/ '{print $1}' | fzf --prompt="pmm>apt>install> ")
        [[ -n "$app" ]] && sudo apt install -y "$app"
        ;;
    Remove)
        app=$(apt list --installed | awk -F/ '{print $1}' | fzf --prompt="pmm>apt>remove> ")
        [[ -n "$app" ]] && sudo apt remove -y "$app"
        ;;
	Purge)
        app=$(apt list --installed | awk -F/ '{print $1}' | fzf --prompt="pmm>apt>purge> ")
        [[ -n "$app" ]] && sudo apt purge -y "$app"
        ;;
	Clean)
		sudo apt-get autoremove -y
		;;
    *)
        echo "No action selected."
        ;;
esac
