#! /bin/bash
clear
borderGen-pmm "Full Update Script" 93

# Controlla se è eseguito come root, altrimenti rilancia con sudo
if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

borderGen-pmm "PACMAN" 96
# If there's pacman but not yay
if [[ "${availablepmlist}" == *"pacman"* ]] && [[ "${availablepmlist}" != *"yay"* ]]
	then
		clear
		echo -e "\nPlease, install yay\n"
		read -p "Press enter to continue . . ."
		exit
fi
if ! command -v yay 2>&1 >/dev/null
then
	echo -e "pacman could not be found. Skipping this package manager."
else
	yay -Syyu
fi

borderGen-pmm "APT" 91
if ! command -v apt 2>&1 >/dev/null
then
	echo -e "apt could not be found. Skipping this package manager. "
else
	sudo apt update
	sudo apt upgrade
fi

borderGen-pmm "FLATPAK" 94
if ! command -v flatpak 2>&1 >/dev/null
then
	echo -e "flatpak could not be found. Skipping this package manager."
else
	flatpak update
fi


echo -e "\nFinished updating!"
read -p "Press enter to continue . . ."
