#!/bin/bash
pmlist=("apt" "flatpak" "pacman" "yay" "pacseek")
availablepmlist="exit\nfull update"

# Check if package managers in pmlist are executables binaries
for str in ${pmlist[@]}; do
	if command -v $str 2>&1 >/dev/null
		then
			availablepmlist="${availablepmlist}\n${str}"
	fi
done

# If there's pacman but not yay
if [[ "${availablepmlist}" == *"pacman"* ]] && [[ "${availablepmlist}" != *"yay"* ]]
	then
		clear
		echo -e "\nPlease, install yay\n"
		read -p "Press enter to continue . . ."
		exit
fi
# If there's yay but not pacseek
if [[ "${availablepmlist}" == *"yay"* ]] && [[ "${availablepmlist}" != *"pacseek"* ]]
	then
		clear
		echo -e "Installing pacseek as CLI CUI for YAY"
		yay -Syu
		yay -S pacseek
		read -p "Press enter to continue . . ."
fi
if [[ "${availablepmlist}" == *"pacseek"* ]]
	then
		availablepmlist=${availablepmlist//"pacman\n"/} # Rimuovo pacman dalla lista
		availablepmlist=${availablepmlist//"yay\n"/} # Rimuovo yay dalla lista
fi

exitCheck=0
errorMessage=""
while [ $exitCheck = 0 ]
do
	# main switch case
	application=$(echo -e "${availablepmlist}" | fzf --prompt="${errorMessage}pmm> ")
	errorMessage=""
	case "$application" in
	    apt | deb)
			aptpmm
	        ;;
	    flatpak)
			flatpmm
	        ;;
	    pacman | yay | pacseek | arch )
			pacseek
	        ;;
	    "full update" | fu)
	        fupmm
			;;
	    exit)
		exitCheck=1
	        echo "Goodbye!"
	        ;;
	    *)
	        errorMessage=" ERROR: not an entry! "
	        ;;
	esac
done
